### ISSUE TITLE
Title: Unable to find documentation for dash-mantine-components version 0.10.2

### ISSUE THREAD

**Issue by amrohendawi** [snehilvj/dash-mantine-components#170]
### Description:
I am currently using the dash-mantine-components library version 0.10.2 in my Python project, but I am having trouble finding any documentation for this specific version. I have searched the official website of dash-mantine-components, but it does not offer documentation per version, and I am unable to find any other resources online.

As a user, it would be helpful to have access to documentation that corresponds to the specific version of the library I am using, as there may be differences in functionality or usage compared to newer or older versions.

Could you please add an option to view previous documentation versions to the official website or is there an alternative resource that I can refer to?

Library: `dash-mantine-components==0.10.2`

**Comment by AnnMarieW** [comment]
Hi @amrohendawi 

I highly recommend upgrading to the most recent version of dcm since V0.10.2 is no longer supported.

If that's not possible, you could try running the docs app locally and set it to a commit for when 0.10.2 was being used.  https://github.com/snehilvj/dmc-docs

Unfortunately, there are no plans to make the 0.10.2 version of the docs available on-line.
