### ISSUE TITLE
MultiSelect - placeholder does not disappear after selection

### ISSUE THREAD

**Issue by zuyan9** [snehilvj/dash-mantine-components#284]
## Behavior
This can be observed in the official docs:

MultiSelect [doc](https://www.dash-mantine-components.com/components/multiselect#multiselect): placeholder does not disappear after selections have been made.

<img width="628" alt="image" src="https://github.com/snehilvj/dash-mantine-components/assets/7322443/e1524c31-c45d-448d-af5c-36f90e4429ab">

## Expected
While in Select [doc](url): placeholder disappears after a selection is made.

<img width="675" alt="image" src="https://github.com/snehilvj/dash-mantine-components/assets/7322443/35aa8a36-414e-4e8f-a499-dcdf7c6ed953">

dash_mantine_components version: 0.14.3

**Comment by AnnMarieW** [comment]
I agree it looks odd, but it's the same as in the upstream Mantine library.  Check it out in their docs:
https://mantine.dev/core/multi-select/

**Comment by zuyan9** [comment]
> I agree it looks odd, but it's the same as in the upstream Mantine library. Check it out in their docs: https://mantine.dev/core/multi-select/
> 
> Someone brought it up as an issue there, and they say that this is the intended behavior: [mantinedev/mantine#5288 (comment)](https://github.com/mantinedev/mantine/issues/5288#issuecomment-1846845534)

Thanks, I guess it makes sense, I still find it odd and the past behavior is different.
For example, in dash_mantine_components version 0.12, placeholder disappears automatically. This can be observed in the official [doc](https://dmc-docs-0-12.onrender.com/components/multiselect#simple-example):
<img width="445" alt="image" src="https://github.com/snehilvj/dash-mantine-components/assets/7322443/c80159b3-4ccc-4be6-bb09-d3901fc53020">
<img width="445" alt="image" src="https://github.com/snehilvj/dash-mantine-components/assets/7322443/e3853da4-7a5e-4b4f-9ff7-040f1f95f546">

**Comment by AnnMarieW** [comment]
@zuyan9 The dmc V0.12 is based on Mantine 4 and it's again consistent with the upstream Mantine library.
https://v4.mantine.dev/core/multi-select/

Since the dash-mantine-components intends to follow the upstream API, then it's unlikely that this will be fixed here.   But @snehilvj has the final say of course :slightly_smiling_face: I agree that it looks like a bug, but it appears to be their design decision.   I've never seen a multi-select that keeps the placeholder after selections are made.
