### ISSUE TITLE
barChartProps don't work

### ISSUE THREAD

**Issue by AnnMarieW** [snehilvj/dash-mantine-components#294]
This prop should pass props to the underlying chart.  

In this example in the docs, there should be a radius on the bars

https://www.dash-mantine-components.com/components/barchart#bar-props

Similar to:

https://mantine.dev/charts/bar-chart/#bar-props

**Comment by michaelrussell4** [comment]
Yeah I was toying around with the dmc.BarChart component today and found some issues. The hover legend and legend are not formatted correctly. 
Instead of the chart in the documentation example:
![image](https://github.com/user-attachments/assets/aae14b35-a67c-4400-96dd-95d4d92f6edb)
I'm getting:
![image](https://github.com/user-attachments/assets/b7023ae1-267a-4189-8b51-9a78987f6d56)
Not sure if I should make this a separate issue or not.

**Comment by AnnMarieW** [comment]
Hi @michaelrussell4 

Can you make a reproducible example?  It should be possible to make it look like the docs

**Comment by michaelrussell4** [comment]
@AnnMarieW yes I'll make a new issue out of it, though. Sounds like it's a bit different from this one. I'll tag this issue and you in it for reference.
