### ISSUE TITLE
[Feature Request] Support base 64 images in dmc.Avatar

### ISSUE THREAD

**Issue by pip-install-python** [snehilvj/dash-mantine-components#374]
Was trying to use dcc.Upload with dmc.Avatar but it wouldn't work, reading through the docs of dcc.Upload I noticed it uses a base 64 image that is capable of working with html.Image, attempted to use this base 64 upload in dmc.Image and it works fine, just would be a nice improvement to have dmc.Avatar also support base 64 images.

**Comment by AnnMarieW** [comment]
This is caused by an overly restrictive sanitizeUrl.

As with `dmc.Image` and` dmc.BackgroundImage `  It is not necessary to sanitize the URL of the `dmc.Avatar` because it renders as an html Img. 

See all the details and background discussion in https://github.com/snehilvj/dash-mantine-components/issues/256
