### ISSUE TITLE
Decimal step in range slider

### ISSUE THREAD

**Issue by pahoffmann** [snehilvj/dash-mantine-components#397]
When experimenting with the Range-Slider, i found, that only the normal Slider works with decimal steps, while the Range-Slider does not. It seems like there is an issue where a value < 1 is interpreted as 0 and therefore the RangeSlider does not slide at all for these values. I am using version 0.14.6.

Code to reproduce:

Slider working with decimals:
`dmc.Slider(
    min=0,
    max=1,
    step=0.1
),`

Not working for RangeSlider:

`dmc.RangeSlider(
    min=0,
    max=1,
    step=0.1
),`

Cheers and thanks for looking into it,

Patrick

**Comment by AnnMarieW** [comment]
Hi @pahoffmann 
That's a strange one!  It had me stumped for a few minutes.

The issue is the `RangeSlider` has a `minRange` prop that Mantine sets with a default of 10.  This breaks the range slider if the `minRange` is greater than the `max`.

Not sure when that changed, but our docs are very out of date.   (We :heart: pull requests :slightly_smiling_face: )

Mantine Slider docs  https://mantine.dev/core/slider/
DMC Slider docs https://www.dash-mantine-components.com/components/slider

GitHub dmc-docs slider - https://github.com/snehilvj/dmc-docs/tree/main/docs/slider


Since in DMC, this fails silently, we should also add an error message when the `minRange` is greater than the `max`.

**Comment by pahoffmann** [comment]
Hi @AnnMarieW,

thanks for the quick response! Setting minRange to the same value as the step solves my issue. 
I am just wondering - what is the minRange parameter actually used for?
I would love to contribute, but i am on a tight schedule atm. Maybe i will find the time in a couple of days.

Thanks again!

**Comment by AnnMarieW** [comment]
The slider section is now updated and includes a note about the `minRange` and `max` props
