### ISSUE TITLE
Feature Request and Guidance Request

### ISSUE THREAD

**Issue by sssaha** [snehilvj/dash-mantine-components#464]
Not sure it is possible - but is there a plan to add a TreeSelect component under DMC? 

Currently I am using the Tree Select component from here https://ant.design/components/tree-select - and I was hoping to see how can I create the same label format like DMC Select? I was trying to do it via a ClassName of dmc.Text?  For example how can I create a DMC Text that has the same style as the label of a DMC Select component?

**Comment by AnnMarieW** [comment]
Hi @sssaha 

There is a PR for a Tree component here:  https://github.com/snehilvj/dash-mantine-components/pull/460, so that will get part way there.   Mantine does not have a Tree Select component, but when it does, we'll add it here too.

I'm not familiar with the ant.design library, so I'm not able to help style those components.    You could try asking over there or on the Dash community forum or the DMC discord.

**Comment by AnnMarieW** [comment]
Hi @sssaha 

Just FYI - there is now a `dmc.Tree` component in 0.15.3 https://www.dash-mantine-components.com/components/tree

Also, if you would like to add a label to components of other libraries so the style is similar to DMC components, you can use the new `dmc.InputWrapper` component:  https://www.dash-mantine-components.com/components/inputwrapper
